# Generated by Django 5.0.4 on 2024-05-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=255, unique=True)),
                ('url_hash', models.TextField(max_length=255, unique=True)),
            ],
        ),
    ]
